// <auto-generated />
using System;
using KonXProWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonXProWebApp.Data.Migrations
{
    [DbContext(typeof(db_9f8bee_konxdevContext))]
    partial class db_9f8bee_konxdevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KonXProWebApp.Models.PermitIntel.AlertPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AlertFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Boroughs")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTypes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("MaxCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trades")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AlertPreferences", "dbo", t =>
                        {
                            t.HasTrigger("AlertPreferences_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.PermitIntel.IngestionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSocrataTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordsIngested")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IngestionLogs", "dbo", t =>
                        {
                            t.HasTrigger("IngestionLogs_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.PermitIntel.SavedLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DobjobFilingId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DobjobFilingId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DobjobFilingId")
                        .IsUnique();

                    b.ToTable("SavedLeads", "dbo", t =>
                        {
                            t.HasTrigger("SavedLeads_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.PermitIntel.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasFilter("[StripeSubscriptionId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions", "dbo", t =>
                        {
                            t.HasTrigger("Subscriptions_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.BlogContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("SourceID");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentId");

                    b.ToTable("BlogContent", "dbo", t =>
                        {
                            t.HasTrigger("BlogContent_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.BlogFeedSource", b =>
                {
                    b.Property<int>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedId"));

                    b.Property<string>("FeedCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedId");

                    b.ToTable("BlogFeedSources", "dbo", t =>
                        {
                            t.HasTrigger("BlogFeedSources_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.DobViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bin");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("block");

                    b.Property<int>("Boro")
                        .HasColumnType("int")
                        .HasColumnName("boro");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("house_number");

                    b.Property<string>("IsnDobBisViol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isn_dob_bis_viol");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("issue_date");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lot");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street");

                    b.Property<string>("ViolationCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_category");

                    b.Property<string>("ViolationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_number");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_type");

                    b.Property<string>("ViolationTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_type_code");

                    b.HasKey("Id");

                    b.ToTable("DOB_Violations", "dbo", t =>
                        {
                            t.HasTrigger("DOB_Violations_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.DobjobFiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdultEstab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantLicenseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantProfessionalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantsFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantsLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Approved")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Assigned")
                        .HasColumnType("datetime");

                    b.Property<string>("Bin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buildingclass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BUILDINGCLASS");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityOwned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurbCut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DobrunDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DOBRunDate");

                    b.Property<string>("DocNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EFilingFiled")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("eFilingFiled");

                    b.Property<string>("EnlargementSqfootage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EnlargementSQFootage");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingDwellingUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingNoofStories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingOccupancy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingZoningSqft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FireAlarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FireSuppression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelBurning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelStorage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FullyPaid")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FullyPermitted")
                        .HasColumnType("datetime");

                    b.Property<string>("Gisbin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GISBIN");

                    b.Property<string>("Giscensustract")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GISCENSUSTRACT");

                    b.Property<string>("Giscouncildistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GISCOUNCILDISTRICT");

                    b.Property<string>("Gislatitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GISLATITUDE");

                    b.Property<string>("Gislongitude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GISLONGITUDE");

                    b.Property<string>("Gisntaname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GISNTANAME");

                    b.Property<string>("HorizontalEnlrgmt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InitialCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobNum")
                        .HasColumnType("int");

                    b.Property<string>("JobStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobStatusDescrp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jobnogoodcount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JOBNOGOODCOUNT");

                    b.Property<string>("Jobs1no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JOBS1NO");

                    b.Property<string>("Landmarked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestActionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LeadScore")
                        .HasColumnType("int")
                        .HasColumnName("LeadScore");

                    b.Property<string>("Littlee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoftBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mechanical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NonProfit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnersBusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnersFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnersHouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnersHouseStreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnersLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnersPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Paid")
                        .HasColumnType("datetime");

                    b.Property<string>("Pcfiled")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PCFiled");

                    b.Property<string>("Plumbing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreFilingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProfessionalCert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedDwellingUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedNoofStories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedOccupancy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedZoningSqft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Signoffdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SIGNOFFDATE");

                    b.Property<string>("SiteFill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialDistrict1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialDistrict2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialactiondate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SPECIALACTIONDATE");

                    b.Property<string>("Specialactionstatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SPECIALACTIONSTATUS");

                    b.Property<string>("Sprinkler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standpipe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetFrontage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalEstFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Totalconstructionfloorarea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TOTALCONSTRUCTIONFLOORAREA");

                    b.Property<string>("VerticalEnlrgmt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Withdrawalflag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WITHDRAWALFLAG");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoningDist1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoningDist2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoningDist3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DOBJobFilings", "dbo", t =>
                        {
                            t.HasTrigger("DOBJobFilings_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.EcbViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AggravatedLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aggravated_level");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_due");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bin");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("block");

                    b.Property<int>("Boro")
                        .HasColumnType("int")
                        .HasColumnName("boro");

                    b.Property<string>("CertificationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("certification_status");

                    b.Property<string>("EcbViolationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ecb_violation_number");

                    b.Property<string>("EcbViolationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ecb_violation_status");

                    b.Property<DateTime>("HearingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hearing_date");

                    b.Property<string>("HearingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hearing_status");

                    b.Property<string>("HearingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hearing_time");

                    b.Property<string>("InfractionCode1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("infraction_code1");

                    b.Property<string>("IsnDobBisExtract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isn_dob_bis_extract");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("issue_date");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lot");

                    b.Property<decimal>("PenalityImposed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("penality_imposed");

                    b.Property<string>("RespondentCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respondent_city");

                    b.Property<string>("RespondentHouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respondent_house_number");

                    b.Property<string>("RespondentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respondent_name");

                    b.Property<string>("RespondentStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respondent_street");

                    b.Property<string>("RespondentZip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respondent_zip");

                    b.Property<string>("SectionLawDescription1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section_law_description1");

                    b.Property<DateTime>("ServedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("served_date");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("severity");

                    b.Property<string>("ViolationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_description");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_type");

                    b.HasKey("Id");

                    b.ToTable("ECB_Violations", "dbo", t =>
                        {
                            t.HasTrigger("ECB_Violations_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.HomeImprovementContractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressBuilding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressStreetName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressZip")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Borough")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BusinessUniqueId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DbaTradeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HomeImprovementContractors", t =>
                        {
                            t.HasTrigger("HomeImprovementContractors_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.HpdViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apartment");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_date");

                    b.Property<string>("Bin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bin");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("block");

                    b.Property<string>("Boro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("boro");

                    b.Property<string>("BoroId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("boro_id");

                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("building_id");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("house_number");

                    b.Property<DateTime?>("InspectionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("inspection_date");

                    b.Property<string>("Lot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lot");

                    b.Property<string>("NovDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nov_description");

                    b.Property<DateTime?>("OriginalCertifyByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("original_certify_by_date");

                    b.Property<DateTime?>("OriginalCorrectByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("original_correct_by_date");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_name");

                    b.Property<string>("ViolationId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_id");

                    b.Property<string>("ViolationStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_status");

                    b.Property<string>("ViolationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("violation_type");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.ToTable("HPD_Violations", "dbo", t =>
                        {
                            t.HasTrigger("HPD_Violations_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.ServiceRequest311", b =>
                {
                    b.Property<string>("UniqueKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bbl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComplaintType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncidentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncidentZip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueKey");

                    b.HasIndex("Bbl");

                    b.ToTable("ServiceRequests311", "dbo", t =>
                        {
                            t.HasTrigger("ServiceRequests311_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.VwBasicTierDashboard", b =>
                {
                    b.Property<string>("Borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LatestActionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("vwBasicTierDashboard", "dbo", t =>
                        {
                            t.HasTrigger("vwBasicTierDashboard_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.VwDemoDisplay", b =>
                {
                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("vwDemoDisplay", "dbo", t =>
                        {
                            t.HasTrigger("vwDemoDisplay_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.VwFreeTierDashboard", b =>
                {
                    b.Property<string>("Borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LatestActionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("vwFreeTierDashboard", "dbo", t =>
                        {
                            t.HasTrigger("vwFreeTierDashboard_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.VwHighTierDashboard", b =>
                {
                    b.Property<string>("Borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HouseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LatestActionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("vwHighTierDashboard", "dbo", t =>
                        {
                            t.HasTrigger("vwHighTierDashboard_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.db_9f8bee_konxdev.VwMidTierDashboard", b =>
                {
                    b.Property<string>("Borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HouseNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LatestActionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("vwMidTierDashboard", "dbo", t =>
                        {
                            t.HasTrigger("vwMidTierDashboard_Trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonXProWebApp.Models.PermitIntel.SavedLead", b =>
                {
                    b.HasOne("KonXProWebApp.Models.db_9f8bee_konxdev.DobjobFiling", "DobjobFiling")
                        .WithMany()
                        .HasForeignKey("DobjobFilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DobjobFiling");
                });
#pragma warning restore 612, 618
        }
    }
}
